### ISSUE TITLE
[Review][Turing Data Story] Election model 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#113]
# Story Review:  

**Story Name:** US election model

**Submitting Author**: @edaub 

**Pull Request:** #111 

**Reviewers:** @samvanstroud @kevinxufs 

## Reviewer instructions & questions

@samvanstroud @kevinxufs , please carry out your review in this issue by updating the checklist below, and writing new comments in case you have any questions. If you cannot edit the checklist please:

- Make sure you're logged in to your GitHub account
- Be sure to accept the invite at this URL: https://github.com/alan-turing-institute/TuringDataStories/settings/access

Any questions, concerns or suggestions regarding the review process please let @crangelsmith, @DavidBeavan or @samvanstroud know.

✨ Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest ✨

#### Code of conduct
- [ ] I confirm that I read and will adhere to the Turing Data Stories [code of conduct](https://github.com/alan-turing-institute/TuringDataStories/blob/master/CODE_OF_CONDUCT.md).

#### General checks
- [ ]  **Notebook:** Is the source code for this data story available as a notebook in the linked pull request?
- [ ]  **Contribution and authorship:** Are the authors clearly listed? Does the author list seem appropriate and complete?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis of open data? Is the story aligned with the Turing Data Stories [vision statment](https://github.com/alan-turing-institute/TuringDataStories#our-vision)?

#### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited with a link?
- [ ] Is the data provenance documented and transparent?

#### Pedagogy
- [ ] Does the story demonstrate some specific data analysis or visualisation techniques?
- [ ] Are these techniques well motivated?
- [ ] Are these techniques well implemented?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the notebook has a introduction section motivating the story?
- [ ] Does the notebook has a conclusion section discussing the main insight from the stories?
- [ ] Is the paper well written (it does not require editing for structure, language, or writing quality)?

#### Context
- [ ] Does the story give an insight into some societal issue?
- [ ] Is the context around this issue well referenced (newspaper articles, scientific papers, etc.)?

## AOB

There are a few other checkboxes in the PR #111  proposed by @edaub that should be checked: 

- [ ] Does the model give enough context about the election, both for the US election format in general as well as the particular situation that arose in 2020?
- [ ] Do I give enough detail about the linear regression models, and is it clear why it is hard to draw conclusions from them?
- [ ] Is there enough background on Bayesian Inference for non-specialists?
- [ ] Is it clear what a hierarchical model is and why it makes sense in this situation?
- [ ] Is the model itself described in sufficient detail? Too much detail?
- [ ] Do the results get tied back to the election narrative enough to make the story of interest to readers that don't care as much about the model details?
- [ ] Is the coding style sensible? I try to wrap everything into functions out of habit, but sometimes this makes notebooks harder to read.
- [ ] Everything looks ok?

**Comment by kevinxufs** [comment]
(IN PROGRESS)

## Review Checklist

#### Code of conduct
- [ ] I confirm that I read and will adhere to the Turing Data Stories [code of conduct](https://github.com/alan-turing-institute/TuringDataStories/blob/master/CODE_OF_CONDUCT.md).

#### General checks
- [ ]  **Notebook:** Is the source code for this data story available as a notebook in the linked pull request?
- [ ]  **Contribution and authorship:** Are the authors clearly listed? Does the author list seem appropriate and complete?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis of open data? Is the story aligned with the Turing Data Stories [vision statment](https://github.com/alan-turing-institute/TuringDataStories#our-vision)?


#### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited with a link?
- [ ] Is the data provenance documented and transparent?

#### Pedagogy
- [ ] Does the story demonstrate some specific data analysis or visualisation techniques?
- [ ] Are these techniques well motivated?
- [ ] Are these techniques well implemented?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the notebook has a introduction section motivating the story?
- [ ] Does the notebook has a conclusion section discussing the main insight from the stories?
- [ ] Is the paper well written (it does not require editing for structure, language, or writing quality)?


#### Context
- [ ] Does the story give an insight into some societal issue?
- [ ] Is the context around this issue well referenced (newspaper articles, scientific papers, etc.)?


## AOB

There are a few other checkboxes in the PR #111  proposed by @edaub that should be checked: 

- [ ] Does the model give enough context about the election, both for the US election format in general as well as the particular situation that arose in 2020?
- [ ] Do I give enough detail about the linear regression models, and is it clear why it is hard to draw conclusions from them?
- [ ] Is there enough background on Bayesian Inference for non-specialists?
- [ ] Is it clear what a hierarchical model is and why it makes sense in this situation?
- [ ] Is the model itself described in sufficient detail? Too much detail?
- [ ] Do the results get tied back to the election narrative enough to make the story of interest to readers that don't care as much about the model details?
- [ ] Is the coding style sensible? I try to wrap everything into functions out of habit, but sometimes this makes notebooks harder to read.
- [ ] Everything looks ok?

**Comment by samvanstroud** [comment]
(IN PROGRESS)


## Review Checklist

#### Code of conduct
- [ ] I confirm that I read and will adhere to the Turing Data Stories [code of conduct](https://github.com/alan-turing-institute/TuringDataStories/blob/master/CODE_OF_CONDUCT.md).

#### General checks
- [ ]  **Notebook:** Is the source code for this data story available as a notebook in the linked pull request?
- [ ]  **Contribution and authorship:** Are the authors clearly listed? Does the author list seem appropriate and complete?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis of open data? Is the story aligned with the Turing Data Stories [vision statment](https://github.com/alan-turing-institute/TuringDataStories#our-vision)?


#### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited with a link?
- [ ] Is the data provenance documented and transparent?

#### Pedagogy
- [ ] Does the story demonstrate some specific data analysis or visualisation techniques?
- [ ] Are these techniques well motivated?
- [ ] Are these techniques well implemented?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the notebook has a introduction section motivating the story?
- [ ] Does the notebook has a conclusion section discussing the main insight from the stories?
- [ ] Is the paper well written (it does not require editing for structure, language, or writing quality)?


#### Context
- [ ] Does the story give an insight into some societal issue?
- [ ] Is the context around this issue well referenced (newspaper articles, scientific papers, etc.)?


## AOB

There are a few other checkboxes in the PR #111  proposed by @edaub that should be checked: 

- [ ] Does the model give enough context about the election, both for the US election format in general as well as the particular situation that arose in 2020?
- [ ] Do I give enough detail about the linear regression models, and is it clear why it is hard to draw conclusions from them?
- [ ] Is there enough background on Bayesian Inference for non-specialists?
- [ ] Is it clear what a hierarchical model is and why it makes sense in this situation?
- [ ] Is the model itself described in sufficient detail? Too much detail?
- [ ] Do the results get tied back to the election narrative enough to make the story of interest to readers that don't care as much about the model details?
- [ ] Is the coding style sensible? I try to wrap everything into functions out of habit, but sometimes this makes notebooks harder to read.
- [ ] Everything looks ok?

**Comment by samvanstroud** [comment]
Hi @edaub, thanks for this super informative and interesting story. It's a really powerful, yet accessible, example of Bayesian Inference applied to the real world. I think people (myself included before reading) may hear the words "Hierarchical Bayesian Modelling" feel inclined to run the other way, but I think you do a fantastic job of motivating and elegantly demonstrating the power of these techniques. I learnt a lot from reading. I have just a few comments, below.

1. In terms of data provenance, the GitHub site you link to is a little thin on details. Given the level of misinformation around this election, maybe it is additionally worth pointing to the original source (which is a relatively well known institution) where the data is scraped from? This also helps to tick the box on linking to external context around the issue. (I think this page would do: https://www.nytimes.com/interactive/2020/11/03/us/elections/forecast-uncounted-votes-president.html). 

2. Which feature of your model allows for the quantification of uncertainty on the final vote margin? Is it the hierarchical nature nature specifically? Or would it be possible to get uncertainties without a hierarchical model? If the former, I wonder what aspect of this problem requires a hierarchical model to get uncertainties (my understanding is that some understanding of uncertainties comes even with non hierarchical Bayesian models).

3. I think you are maybe missing a word in the sentence " to be slightly different such that more likely to give a democratically-leaning distribution" (I will try to suggest a change directly in the PR)

4. Could it be clearer to normalise your probability distribution histograms to unit area, so that y axis scale seems more in line with what readers may expect from a pdf? (I appreciate that the area is indicating that you are building your pdfs from many samples... maybe just a mention that this is what is happening would suffice?).

5. The "extract_n_k_trials" function is a little opaque to me. Perhaps you could elaborate on the use of bernoulli trials in this context (I think the function docstring is the only mention, readers might be left wondering). Additionally, there are some checks on the validity of the data. Could these be explained? For example what is a "set" in this context and what does it mean for it to "make sense"? (i.e. the idea behind the "keep = (n > 0)*(k >= 0)*(k <= n)" line).

Thanks again for an enjoyable read!

**Comment by edaub** [comment]
Thanks, @samvanstroud -- super useful comments and I agree wholeheartedly with those suggestions. I'll give a go at a revision (probably when I get any additional comments from @kevinxufs).

**Comment by kevinxufs** [comment]
@edaub 

Many thanks for submitting this story, a really interesting one both in terms of the techniques used but also the societal context. As a non specialist my comments are largely targetted at the AOB you suggested, as well as other areas where I think additional explanation would be appreciated. As a note, I have previously very little experience with Bayseian modelling so I found the explanation very helpful, but I still felt uncertain - after reading the story - that I could properly explain the work or implement the technique myself (e.g. by modifying the notebook). I think as our stories get varied and more sophisticated, the expectation of the reader being able to effectively play around with the notebook is maybe optimistic. I think we should aim for the reader being able to broadly explain what was done.

1) `Does the model give enough context about the election, both for the US election format in general as well as the particular situation that arose in 2020?`

Yes I think so, although I think slightly more context with regards to an 'electoral college' system might be helpful. I think someone without any understanding of US electoral system might need to do additional research to understand the background.

2)` Do I give enough detail about the linear regression models, and is it clear why it is hard to draw conclusions from them?`

I think the explanation is very good, but I think there a few points on data clarity that could be helpful. I noted two questions (possibly my own misunderstanding).

a) It surprised me that as we got closer to the final date, some of the votes actually started decreasing (e.g. from 2473707 to 2473633). I originally thought that the drip of votes would lead to the votes only being able to increase. I found this a bit confusing.

b) It was mentioned at one point (paragraph 5) that the linear regression was not really accurate as it predicted different results from the final margin. I think it would be helpful for us to note what the final margin is. Was the idea that given our knowledge of the future, the past linear regression analysis would have been incorrect given said past knowledge?

3 `Is there enough background on Bayesian Inference for non-specialists?`

I think there could be more. I think I understood the rough idea of as we get more data we update what we think the voter probability distribution, but I think it could be spelled our a bit more each of the aspects. E.g. explaining what the prior means (p|\theta) specifically for our context would have been helpful. I found the discussion around likelihood a bit hard to understand.

The beta distribution was explained but I wasn't quite sure why you were using the log normal distribution and I think more explanation could have been helpful. I wasn't quite clear why the samples were probability distributions themselves - was it because you were sampling based on a given `a` and `b` value?

4)` Is it clear what a hierarchical model is and why it makes sense in this situation?`

The main idea was explained well I thought and motivated effectively. I guess one question I had (and this is really just lack of knowledge I think) is why should we use this 'probability of a probability' view instead of just taking some kind of expectated value / mean? A short line clarifying this thought might be helpful.

5) `Do the results get tied back to the election narrative enough to make the story of interest to readers that don't care as much about the model details?`

Very much so - very interesting and I understood the broad idea. Although to note that I was a bit disappointed that I couldn't see the animations (I appreciate the length of time it takes to compute them). Could you perhaps insert some kind of pre processed image instead?

6) ` Is the coding style sensible? I try to wrap everything into functions out of habit, but sometimes this makes notebooks harder to read.`

Seemed sensible - I think a small bit of explanation on the plot code would have been helpful. E.g. stuff like axis etc. Some of the code at the very end (animations) I found a bit harder to understand what was happening.

7) `Everything looks ok?`

Yes, I think it aesthetically looks very good.

Thanks again Eric for the great story.

**Comment by edaub** [comment]
Appreciate the feedback -- I've made my edits to the story, and am happy to articulate what I have changed in a detailed response if that would be helpful. Should I spell that out here, or in the PR?

**Comment by samvanstroud** [comment]
Hi @edaub, that sounds great, posting it here would be perfect, thanks.

**Comment by edaub** [comment]
Hi @samvanstroud and @kevinxufs,

Below are my responses to the reviews. I've done a thorough revision in response, and I've highlighted how I have improved the story based on your helpful comments. I've pushed the updated story in #111 (see the latest in the markdown file as I don't want to add any bloat by re-running the notebooks until the story is finalized).

----------------------

> In terms of data provenance, the GitHub site you link to is a little thin on details. Given the level of misinformation around this election, maybe it is additionally worth pointing to the original source (which is a relatively well known institution) where the data is scraped from? This also helps to tick the box on linking to external context around the issue. (I think this page would do: https://www.nytimes.com/interactive/2020/11/03/us/elections/forecast-uncounted-votes-president.html).

Thanks, this is helpful. I have added some details around this in the "Data" section and linked to the page you mention.

> Which feature of your model allows for the quantification of uncertainty on the final vote margin? Is it the hierarchical nature nature specifically? Or would it be possible to get uncertainties without a hierarchical model? If the former, I wonder what aspect of this problem requires a hierarchical model to get uncertainties (my understanding is that some understanding of uncertainties comes even with non hierarchical Bayesian models).

The main contribution to the final uncertainty comes from relaxing the assumption that the vote probability is a single number (either as a regression slope or an unknown parameter) and letting it be a distribution. A hierarchical model is not the only way to do this, but as I tried to elaborate in the story it is an effective method of making the model significantly more complicated without adding a ton of parameters. This makes it easier to fit and more robust, but there are probably other ways to do this. I tried to highlight this by expanding the description of hierarchical models and mentioning in the "Model Description" section that relaxing the assumption of a single vote probability is the biggest contribution to the uncertainties. Please let me know if this gets at what you are asking!

> I think you are maybe missing a word in the sentence " to be slightly different such that more likely to give a democratically-leaning distribution."

Fixed.

> Could it be clearer to normalise your probability distribution histograms to unit area, so that y axis scale seems more in line with what readers may expect from a pdf? (I appreciate that the area is indicating that you are building your pdfs from many samples... maybe just a mention that this is what is happening would suffice?).

I mention under the section "Bayesian Inference" that since we are ultimately just drawing samples from probability distributions the vertical scales aren't meaningful in an absolute sense and thus I never label them. Normalizing them correctly is tricky as you need to know the bin size and the number of samples, and I don't think it adds anything since the relative differences are all we care about.

> The "extract_n_k_trials" function is a little opaque to me. Perhaps you could elaborate on the use of bernoulli trials in this context (I think the function docstring is the only mention, readers might be left wondering). Additionally, there are some checks on the validity of the data. Could these be explained? For example what is a "set" in this context and what does it mean for it to "make sense"? (i.e. the idea behind the "keep = (n > 0)(k >= 0)(k <= n)" line).

I've re-named this function, added an in-code comment about why we need to do this, and added some further description in the previous text block about this. Hopefully this makes it clearer.

**Comment by samvanstroud** [comment]
Many thanks @edaub for these comprehensive modifications and replies. Everything looks great from my end, I did spot a few bugs that have been introduced alongside the code changes, suggestions for fixes for these are given in the PR #111.

I will also update the review checklist to include our new ethical review section, but I don't think this will require any further modifications. Hopefully we can have this published very soon!

Thanks again

**Comment by kevinxufs** [comment]
@edaub 

Thanks Eric for these changes. I focused mostly on the text and description side and I found the additional explanation very helpful to understand these issues better.

I'll also update this review once the ethical review process is finalised. The nature of this topic (politics) is always going to be a bit difficult in this regard due to risks of how it can be interpreted.. I think this story was overall very objective and neutral in this regard.

The only area I thought was remotely at risk here was your choice to represent the Biden swing as the positive votes. I think the choice in doing was justified (as the story is about confident we can be in Biden winning over time) and don't see this as a particular ethical issue, I just wanted to flag how this could be interpreted.

**Comment by edaub** [comment]
Thanks for the responses. I agree that politics can be a touchy subject -- perhaps my use of a subjective prior takes on heightened significance because of this. I may in fact revise to more clearly point out that I explicitly try to construct my prior to give a reasonable chance for a large swing in favor of Republicans to try and ensure that the model isn't biased against one party. I'll push a few more changes to finalize and then this should be ready to go.
