### ISSUE TITLE
Thoughts on the story telling side

### ISSUE THREAD

**Issue by DavidBeavan** [alan-turing-institute/TuringDataStories#44]
Possible structure:

# Front matter

* Title
* Authors
* Citation
* Links to Turing Data Study GitHub etc.
* Contents (i.e. anchor links to other sections)

# Intro

* Intro to story
* Story challenge / motivation / thingy

# 'program and prose' i.e. the main section

* Alternate between
  - Good commented code, linted and formatted
  - Explanations of why and what can be seen, always in relation to the story

* Data Sources
* Set-up

# ?Questions, as in for us to think about, not part the story?

* BTW how do we NOT fall into the trendy-topic-trap? e.g. we are discussing Covid-19 AND BLM, and there's push-back against cashing in on these topics
* Challenge of introducing functions before they are used, is not handy for textual narrative
* Can we (CSS) style up the notebook, so it's less techno-looking for a general audience?

**Comment by kevinxufs** [comment]
Thanks Dave. With regards to the question, here are some of my thoughts:

1) To avoid the 'trendy-topic-trap' I think our narrative needs to imply three kinds of things.
a) We need to show that our analyis applies to things that we care about (i.e our discussion on deprivation). This is more of an emotive element.
b) We need to show that our analysis applies to things that are significant. (e.g. Covid)
c) We need to show that the concepts and tools used in our analysis are applicable more broadly.

The narrative we therefore want to present is that we can do good and important analysis. We are people who care about social issues and we want to show case the problems with the hope that our analysis will somehow help solve them. Our stories are not about Covid19 / BLM because we're cashing in on the relevance. It is the contrary - Covid19/BLM are highlighting really key issues that we think are relevant, and we want to use our analysis to explore these issues. Finally, we believe that teaching others how to do this analysis will help solve the overall problem.

I don't think any of this narrative is untrue.

2 / 3) I think we need to make a bit of a decision on which is important, the story of the teaching. Are we thinking of having the story seperate to the notebook?

**Comment by samvanstroud** [comment]
Let's convert this issue into a guideline of how to write a story.

**Comment by DavidBeavan** [comment]
Closing, we've done all this and much much more
